### ISSUE TITLE
现在可以正式在项目中使用吗

### ISSUE THREAD

**Issue by liuce259826** [CodePhiliaX/fastexcel#111]

**Comment by mgl-pub** [comment]
可以啊，不是完全兼任原版吗 原版基础上增强

**Comment by liuce259826** [comment]
在pom文件中如何引入

**Comment by liuce259826** [comment]
![image](https://github.com/user-attachments/assets/b920fcdf-e6e8-4218-8df0-1b657c79db34)
maven库中没有呢

**Comment by mgl-pub** [comment]
> ![image](https://private-user-images.githubusercontent.com/46948903/392203205-b920fcdf-e6e8-4218-8df0-1b657c79db34.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyODIwNzAsIm5iZiI6MTczMzI4MTc3MCwicGF0aCI6Ii80Njk0ODkwMy8zOTIyMDMyMDUtYjkyMGZjZGYtZTZlOC00MjE4LThkZjAtMWI2NTdjNzlkYjM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA0VDAzMDkzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMxYWEyMjMwMGQ2NTM1ZGE1Y2Q3ZGQ2ZWVkNmRlZDY1MjU3MmQwZDk4NTliYjYxYmI1NzlhM2Y4OGIwMDZjODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Xx-DNHNB4tNvEJtID6leDYoUSDMG4xC31-nzmYMjTZo) maven库中没有呢

        <dependency>
            <groupId>cn.idev.excel</groupId>
            <artifactId>fastexcel</artifactId>
            <version>0.0.1</version>
        </dependency> 把之前的阿里的包名前缀换cn.idev即可适配

**Comment by mgl-pub** [comment]
> 在pom文件中如何引入

        <dependency>
            <groupId>cn.idev.excel</groupId>
            <artifactId>fastexcel</artifactId>
            <version>0.0.1</version>
        </dependency> 把之前的阿里的包名前缀换cn.idev即可适配

**Comment by hyson1234567** [comment]
1.0.0的jar何时能在maven中搜索到

**Comment by fwk1010** [comment]
mvnrepository已经有了，排在第一页很后面 @hyson1234567 @liuce259826

**Comment by liuce259826** [comment]
不入maven库终归比较麻烦

**Comment by LeeSmallNorth** [comment]
`<dependency>
    <groupId>cn.idev.excel</groupId>
    <artifactId>fastexcel</artifactId>
    <version>1.0.0</version>
</dependency>`
