### ISSUE TITLE
导入时间数据 有误差

### ISSUE THREAD

**Issue by syc824951** [CodePhiliaX/fastexcel#121]
示例导入：12:00:01这种数据 在识别后  数据会为11:57:21这个样子。 
![image](https://github.com/user-attachments/assets/b164a3ff-7f2d-402a-81d3-d944bfac7022)
![image](https://github.com/user-attachments/assets/a7d0a21d-50e3-453a-ac11-88685c4f7c7b)

**Comment by zhaoyunxing92** [comment]
你版本是多少

**Comment by poo0054** [comment]
你好，你可以提供一个案例吗。在github上面创建一个公开的项目或者把你的源代码和文件粘贴出来

**Comment by psxjoy** [comment]
This appears to be the same issue as [this one](https://github.com/alibaba/easyexcel/issues/3793).
Give it a try to resolve.

**Comment by psxjoy** [comment]
@poo0054 Thanks for getting involved! I’ll assign this issue to you for now. If there’s no response or if my assumptions turn out to be correct, I’ll provide timely status updates.

**Comment by poo0054** [comment]
> This appears to be the same issue as https://github.com/alibaba/easyexcel/issues/3793.
Give it a try to resolve.

稍后我有时间我打算试试==3.3.4==版本看看能不能重现这个错误 `[3793](https://github.com/alibaba/easyexcel/issues/3793)` 



我使用了很多不同格式的单元格。我没有重现该错误。

![image](https://github.com/user-attachments/assets/2e7b6824-5e83-4030-a435-e1df10feb7c7)

版本如下：

> wps
6.13.2(8918)

>  系统
macOS

> idea
2024.3

> fastexcel
1.0.0

> java
jdk1.8.0_421.jdk


> 代码如下
```java

    @Test
    public void testRead() {
        // 写法1：JDK8+ ,不用额外写一个DemoDataListener
        // since: 3.0.0-beta1
        String fileName = TestFileUtil.getPath() + "demo" + File.separator + "demo.xlsx";
        // 这里 需要指定读用哪个class去读，然后读取第一个sheet 文件流会自动关闭
        // 这里默认每次会读取100条数据 然后返回过来 直接调用使用数据就行
        // 具体需要返回多少行可以在`PageReadListener`的构造函数设置
        List<DemoData> objects = EasyExcel.read(fileName, DemoData.class, null).sheet().doReadSync();
        for (DemoData object : objects) {
            System.out.println(JSON.toJSONString(object));
        }

    }

@Getter
@Setter
@EqualsAndHashCode
public class DemoData {
    private String string;
    private String date;
    private Double doubleData;
    private String dateStr;
    private String timeStr;
}

```

**Comment by poo0054** [comment]
@syc824951 你好，可以麻烦提供你的excel文件吗

**Comment by Miucun97** [comment]
试下excel这列的单元格格式改为常规或文本类型。即不用时间格式。单元格依旧保持“年月日 时分秒”的格式。
如果发现excel转换有问题的话，试下直接用公式转换，=text(单元格，“yyyy-mm-dd hh:mm:ss”)。

**Comment by poo0054** [comment]
我在`3.3.4`成功重现了该错误。我现在去排查一下是什么原因导致的。

```java
  @Data
    public static class DemoData {
        @ExcelProperty("出入时间")
        private String timeStr;
    }

    public static void main(String[] args) {
        // 写法1：JDK8+ ,不用额外写一个DemoDataListener
        // since: 3.0.0-beta1
        String fileName = Main.class.getResource("/").getPath() + "demo.xlsx";
        // 这里 需要指定读用哪个class去读，然后读取第一个sheet 文件流会自动关闭
        // 这里默认每次会读取100条数据 然后返回过来 直接调用使用数据就行
        // 具体需要返回多少行可以在`PageReadListener`的构造函数设置
        List<DemoData> objects = EasyExcel
                .read(new File(fileName), DemoData.class, null)
                .excelType(ExcelTypeEnum.XLSX)
                .sheet()
                .doReadSync();
        for (DemoData object : objects) {
            System.out.println(object);
        }
    }
```

```xml
        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>easyexcel</artifactId>
            <version>3.3.4</version>
        </dependency>
```

**Comment by poo0054** [comment]
> This appears to be the same issue as https://github.com/alibaba/easyexcel/issues/3793.
Give it a try to resolve.

You are right, it is `use1904windowing` that affects the result. This picture clearly shows it.

This value is obtained from `globalConfiguration.getUse1904windowing()`. I don't know why the time is `1900` now.
The simplest way is `.use1904windowing(true)` to temporarily solve this problem
I am still studying why the time is `1904`,I need to see if `XMLReader` and `java` have any effect on this

![image](https://github.com/user-attachments/assets/0caf6619-49af-4b33-a2ec-f10b6675ce72)

**Comment by poo0054** [comment]
该 bug 在https://github.com/alibaba/easyexcel/commit/fab7653cd42256adefad49ce6c2624bed3e0f0f1 
`4.0.3`以上版本被修复

**Comment by psxjoy** [comment]
> 该 bug 在[alibaba/easyexcel@fab7653](https://github.com/alibaba/easyexcel/commit/fab7653cd42256adefad49ce6c2624bed3e0f0f1) `4.0.3`以上版本被修复

Very thank for you investigating. I think we should wait few days. If @syc824951 still not response.You can close this issue. :)

**Comment by poo0054** [comment]
我最近又研究了一下

> office2019

![01300ba8c213c1bddcc6d809a37a027](https://github.com/user-attachments/assets/c374007e-2abe-45c6-81ba-6b5668d25112)

![c5d4f146969fc667ad92d45972f047b](https://github.com/user-attachments/assets/2fef4ef6-40ad-4f1e-9efe-1c35ad2abec6)


> wps如下

![image](https://github.com/user-attachments/assets/39253308-6f64-4fd8-bbec-734b9d5e1d0b)

![image](https://github.com/user-attachments/assets/72da237b-e7a6-4187-a868-18f17e6c2b8e)


在`XlsxSaxAnalyser#analysisUse1904WindowDate(XSSFReader xssfReader, XlsxReadWorkbookHolder xlsxReadWorkbookHolder)`中

```java

    private void analysisUse1904WindowDate(XSSFReader xssfReader, XlsxReadWorkbookHolder xlsxReadWorkbookHolder)
        throws Exception {
        if (xlsxReadWorkbookHolder.globalConfiguration().getUse1904windowing() != null) {
            return;
        }
        InputStream workbookXml = xssfReader.getWorkbookData();
        WorkbookDocument ctWorkbook = WorkbookDocument.Factory.parse(workbookXml);
        CTWorkbook wb = ctWorkbook.getWorkbook();
        CTWorkbookPr prefix = wb.getWorkbookPr();
        if (prefix != null && prefix.getDate1904()) {
            xlsxReadWorkbookHolder.getGlobalConfiguration().setUse1904windowing(Boolean.TRUE);
        } else {
            xlsxReadWorkbookHolder.getGlobalConfiguration().setUse1904windowing(Boolean.FALSE);
        }
    }
```

而在`GlobalConfiguration`中，默认为`false`

```java
    public GlobalConfiguration() {
        this.autoTrim = Boolean.TRUE;
        this.use1904windowing = Boolean.FALSE;
        this.locale = Locale.getDefault();
        this.useScientificFormat = Boolean.FALSE;
        this.filedCacheLocation = CacheLocationEnum.THREAD_LOCAL;
    }
```

> 同时存在日期和时间的时候
如果还出现可以试试改变`.use1904windowing(null)`让程序自行决定使用哪种方式(未验证，留个参考)

**Comment by psxjoy** [comment]
Hi，@poo0054 very thanks for your information.I think we can close this issue.
