### ISSUE TITLE
官网字体特效兼容性差，建议恢复为标准无特效字体或选择兼容性特效

### ISSUE THREAD

**Issue by VBPush** [CodePhiliaX/fastexcel#123]
如题/图所示：
微信快速浏览器：
![image](https://github.com/user-attachments/assets/35455f63-b7bc-499b-ae0e-076eb7ebf6ef)
360极速浏览器：
![image](https://github.com/user-attachments/assets/81ced8c3-7ced-4043-ade4-36add5644fd9)

**Comment by JerryFan626** [comment]
收到🫡，立即修复

**Comment by JerryFan626** [comment]
已修复
