### ISSUE TITLE
使用5.2.5版本的poi版本似乎导出图片异常？

### ISSUE THREAD

**Issue by hausen1012** [CodePhiliaX/fastexcel#124]
文件大小有增加，但是图片不展示，可能是api改变导致？

**Comment by zmxccxy** [comment]
1、导出
用wps打开看不到图片（更新到最新版本，可以看到图片，之前反馈过给wps），office看能到。
原因：图片的嵌入、浮动问题。
<img width="841" alt="f0b6137490078f4f3f62a766a9a7e2e" src="https://github.com/user-attachments/assets/2fddfaef-f047-4fa2-9bb5-3a76eb3ea5d6">
我之前用的原生，时间久了，不太记得了，好像换成这个类解决了
![b93ee1d27e7b1f06cd98e7a66bd4fe2](https://github.com/user-attachments/assets/57751395-4e0c-4052-855d-68ebd1f6ad3c)

注意：
浮动的图片在表格里是个相对定位，可以拖动位置，不会随着单元格变化，导入时容易读取。
嵌入的图片在表格是写在单元格里，类似背景图片一样，会随着单元格大小变动而自适应，导入时不容易读取。
