### ISSUE TITLE
从easyExcel 升级到 fastExcel 发现有一堆漏洞

### ISSUE THREAD

**Issue by mage1314** [CodePhiliaX/fastexcel#143]
<dependency>
            <groupId>cn.idev.excel</groupId>
            <artifactId>fastexcel</artifactId>
            <version>1.0.0</version>
            <exclusions>
                <exclusion>
                    <groupId>com.itextpdf</groupId>
                    <artifactId>itext7-core</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.bouncycastle</groupId>
                    <artifactId>bcprov-jdk15on</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.verapdf</groupId>
                    <artifactId>core</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.verapdf</groupId>
            <artifactId>org.verapdf</artifactId>
            <version>1.26.2</version>
        </dependency>  升级完还得排包

**Comment by psxjoy** [comment]
We have removed all `itext` dependencies from the project. Just waiting `1.1.0` release:)
