### ISSUE TITLE
【建议】关于文档和发布

### ISSUE THREAD

**Issue by LeYunone** [CodePhiliaX/fastexcel#165]
因为项目初期是`easyexcel`的plus版本（从中诞生），所以可否在未来的文档或发布日志中将本项目与`easyexcel.final.version`的功能进行一些比较说明。
(这样对堵住一些不愿意升级人的嘴很重要)。迫真.ing

**Comment by psxjoy** [comment]
With every new release, we include relevant fixes and updates. You can find the details in the project’s update.md file.

我们会在每次发布新版本时，提供相关的修复和更新日志。你可以在项目的upadte.md中查看

**Comment by LeYunone** [comment]
> With every new release, we include relevant fixes and updates. You can find the details in the project’s update.md file.
> 
> 我们会在每次发布新版本时，提供相关的修复和更新日志。你可以在项目的upadte.md中查看

好的，感谢回答。(因为在发布1.0版本中没有找到相关的说明)
