### ISSUE TITLE
按模板填充写入excel

### ISSUE THREAD

**Issue by leiyinsong** [CodePhiliaX/fastexcel#166]
原模板：
![image](https://github.com/user-attachments/assets/a4144556-411e-4e3a-b2f0-4793a3a91e8e)
图中圈起来的列会合并多个单元格

但是按照模板填充生成的excel不会自动合并单元格，如下图：
![image](https://github.com/user-attachments/assets/deaab68d-520b-40a7-a63a-7eebfd915c92)

**Comment by tmlx1990** [comment]
> 原模板： ![image](https://private-user-images.githubusercontent.com/33509373/398535814-a4144556-411e-4e3a-b2f0-4793a3a91e8e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxMjMxMTYsIm5iZiI6MTczNTEyMjgxNiwicGF0aCI6Ii8zMzUwOTM3My8zOTg1MzU4MTQtYTQxNDQ1NTYtNDExZS00ZTNhLWIyZjAtNDc5M2EzYTkxZThlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI1VDEwMzMzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1MzA1YThhZWExYmRhN2RkN2M2ZGU5Y2NmNDIwNDVhZjZhM2VkOWM5NTY4M2JhYjI2N2RiNTVjZjljZDUxNzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.cdky9zwNyQvbDQ3dLaVmDE7DCoZC1OAd3cwRGDFG3qg) 图中圈起来的列会合并多个单元格
> 
> 但是按照模板填充生成的excel不会自动合并单元格，如下图： ![image](https://private-user-images.githubusercontent.com/33509373/398536165-deaab68d-520b-40a7-a63a-7eebfd915c92.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxMjMxMTYsIm5iZiI6MTczNTEyMjgxNiwicGF0aCI6Ii8zMzUwOTM3My8zOTg1MzYxNjUtZGVhYWI2OGQtNTIwYi00MGE3LWE2M2EtN2VlYmZkOTE1YzkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI1VDEwMzMzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwNWYwNWMwOThjMmI0OTkwY2FjN2Q1NjQxY2Q3MWFkNTNhYjhmZjdiOGRmOTUzMDZjYmQ2ZmI2ZWJlOGUxYjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.DNQVabvxCRWTBfUR-HeE3VknMo5_EAYCxS3u7nATEWc)

您好，建议修改下模板，把合并的列改成单列。如果不改模板，需要自定义一个单元格合并来处理。

public class CustomMergeStrategy implements CellWriteHandler {

    @Override
    public void afterCellDispose(CellWriteHandlerContext context) {
        // 获取当前单元格
        Cell currentCell = context.getCell();
        // 获取当前行
        Row currentRow = currentCell.getRow();
        // 获取当前sheet
        Sheet currentSheet = currentRow.getSheet();
        // 获取当前行的索引
        int rowIndex = currentRow.getRowNum();
        // 如果不是第一行，则合并第一列和第二列
        if (rowIndex != 0) {
            // 合并第一列和第二列
            currentSheet.addMergedRegionUnsafe(
                    new CellRangeAddress(
                            rowIndex, rowIndex, 1, 2
                    )
            );
        }
    }
}

然后填充的时候加入下边这段：
<img width="906" alt="image" src="https://github.com/user-attachments/assets/fb8d0743-8252-4412-89de-e46579dea898" />

**Comment by leiyinsong** [comment]
好的，谢谢。目前是把合并的列改成单列了
